#' Output the proof-of concept (PoC) testing and the target dose.
#'
#' This function will conduct MCPMod analysis and return the result of the PoC testing of whether there is a significant dose-response relationship and the target dose, e.g., the minimum effective dose based on the clinically meaningful effect size.
#' @details Author: Qing Zhao
#' @param sim.obj A data frame generated by `sim_dat` (recommended) that contains a dose variable and a response variable (when `type` = "normal") that serve as the input of `MCPMod`. 
#' @param dose Either a vector specifying dose values or names of variables in the data frame specified in `data` (when `type` = "normal"), or a vector of the dose levels generated by `gen_design` (when `type` = "general") that serve as the input of `MCPMod`. 
#' @param resp Either a vector specifying response values or names of variables in the data frame specified in `data` (when `type` = "normal"), or a vector of the estimates at the doses (when`type` = "general")that serve as the input of `MCPMod`.  
#' @param data Data frame containing the variables referenced in dose and resp. If `data` is not specified, it is assumed that `dose` and `resp` are vectors specifying dose and response values.
#' @param S The covariance matrix of `resp` when `type` = "general".
#' @param type Determines whether inference is based on MCPMod applied on normally distributed response variable (when `type` = "normal"), or estimates at the doses and their covariance matrix and degrees of freedom that are specified in `resp`, `S`, and `df` through Generalized MCPMod (when `type` = "general").
#' @param Mods.obj.cand An object of class `Mods` that is used to specify the candidate dose-response models. See `Mods` for details.
#' @param Delta A numeric value indicating the clinically meaningful effect size.
#' @param selModel An optional character vector specifying the model selection criterion for dose estimation. Possible values are "AIC", "maxT", and "aveAIC" (recommended). For `type` = "general", the "gAIC" is used.
#' @param ... Additional arguments to `MCPMod`, for example, placAdj, alpha, alternative, etc.
#' @return A data frame that contains results for PoC (Proof-of-Concept) and MED (Minimum Effective Dose).
#' @import DoseFinding
#' @export 
#'
#' @examples
#' \dontrun{
#' # when the response variable is normal 
#' gd.obj <- gen_design(dls = c(0, 6, 12, 18, 30), ngrp.equal = 60)
#' mods.true <- DoseFinding::Mods(sigEmax = c(6.5, 2.2), doses = gd.obj$dls, placEff = 0, maxEff = 1)
#' sds <- c(0.2, 0.6, 0.6, 0.6, 0.6)
#' dat <- sim_dat(dls = gd.obj$dls, ntot = gd.obj$ntot, ngrp = gd.obj$ngrp, Mods.obj.true = mods.true, sds = sds)

#' # when the response variable is binomial
#' gd.obj <- gen_design(dls = c(0, 4, 7, 10), ntot = 300, ratio =  c(2, 1, 2, 2))
#' mods.true <- DoseFinding::Mods(emax = 10, doses = gd.obj$dls, placEff = -1, maxEff = 1)
#' dat <- sim_dat(dls = gd.obj$dls, ntot = gd.obj$ntot, ngrp = gd.obj$ngrp, Mods.obj.true = mods.true, type = "binomial")
#'}

analy_MCPMod <- function(sim.obj = NULL, dose = NULL, resp = NULL, data = NULL, Mods.obj.cand, S = NULL, type = "normal", Delta, selModel = "aveAIC", ...){
  
  if (is.null(sim.obj) == F & is.null(dose) == T & is.null(resp) == T & is.null(data) == T){
    data <-  sim.obj
    dose <- data$dose
  } else if (is.null(sim.obj) == T & is.null(dose) == F & is.null(resp) == F & is.null(data) == T){
    if (length(dose) != length(resp)){
      stop("Dose and response are required to be vectors of equal length specifying dose and response values, if 'data' is not specified.")
    }
  }
  dls <- unique(dose)
  fmod <- DoseFinding::MCPMod(dose, resp, data, models = Mods.obj.cand, S = S, type = type, Delta = Delta, selModel = selModel, ...)
  poc <- ifelse(min(attr(fmod$MCTtest$tStat, "pVal")) < 0.05, 1, 0)
  dseq <- seq(dls[1], dls[length(dls)], by=0.005)
  if (length(fmod$selMod)> 0) {
    mod.pred <- do.call("cbind", predict(fmod, doseSeq=dseq, predType="effect-curve", se.fit=F))
    wtd.pred <- mod.pred %*% fmod$selMod
    med <- dseq[which(wtd.pred >= Delta)[1]]
  } else {
    med <- NA
  }
  res <- data.frame(poc, med)
  return(res)
}